//! Build script for admin dashboard static files.
//!
//! Embeds the `www/apps/admin/dist/` contents into the binary at compile time
//! (include_bytes!), so the runtime needs NO filesystem dependency on dist.
//! This fixes the prod-image flaw where ADMIN_DIST_DIR pointed at an absolute
//! build-time path (/workspace/...) that doesn't exist in the runtime image.

use std::fs;
use std::path::PathBuf;

fn main() {
    // Only process when admin-dashboard feature is enabled
    #[cfg(feature = "admin-dashboard")]
    {
        // Resolve dist/ relative to workspace root
        let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
        let dist_dir = manifest_dir.join("../../www/apps/admin/dist");
        let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

        if dist_dir.exists() {
            // Generate a module embedding all dist files as byte arrays.
            // Keys are relative paths ("index.html", "assets/x.js"); values are
            // include_bytes! references into this generated file.
            let mut entries: Vec<(String, String)> = Vec::new();
            collect_files(&dist_dir, &dist_dir, &mut entries);
            entries.sort();

            let mut code =
                String::from("// AUTO-GENERATED by build.rs — embedded admin dist (do not edit)\n");
            for (i, (rel, abs)) in entries.iter().enumerate() {
                let line = format!("pub static FILE_{i}: &[u8] = include_bytes!(\"{abs}\");");
                code.push_str(&line);
                code.push('\n');
            }
            code.push_str("pub static FILES: &[(&str, &[u8])] = &[\n");
            for (i, (rel, _)) in entries.iter().enumerate() {
                code.push_str(&format!("    (\"{rel}\", FILE_{i}),\n"));
            }
            code.push_str("];\n");

            let gen_path = out_dir.join("embedded_admin_dist.rs");
            fs::write(&gen_path, code).expect("write embedded_admin_dist.rs");
            println!("cargo:rustc-env=ADMIN_DIST_EMBED={}", gen_path.display());
            println!("cargo:rerun-if-changed=../../www/apps/admin/dist");
        } else {
            // ponytail: warn but don't fail — admin SPA is optional
            println!(
                "cargo:warning=admin dist/ not found at {} — run `pnpm build` in www/ first",
                dist_dir.display()
            );
        }
    }
    #[cfg(not(feature = "admin-dashboard"))]
    {
        // No-op when feature is disabled
    }
}

/// Recursively collect (relative_path, absolute_path) for all files under root.
#[allow(dead_code)] // 仅 admin-dashboard feature 路径使用；默认姿态无引用（clippy -D 债清偿 09-18）
fn collect_files(root: &PathBuf, dir: &PathBuf, out: &mut Vec<(String, String)>) {
    if let Ok(rd) = fs::read_dir(dir) {
        for entry in rd.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_files(root, &path, out);
            } else {
                let rel = path
                    .strip_prefix(root)
                    .expect("path under root")
                    .to_string_lossy()
                    .replace('\\', "/");
                out.push((rel, path.to_string_lossy().replace('\\', "/")));
            }
        }
    }
}
